package com.orasaka.core.model;

import java.util.Map;

/**
 * Unified chat response record for all AI interactions.
 *
 * @param content The text content generated by the AI model.
 * @param conversationId The session ID this response belongs to.
 * @param metadata Metadata associated with the response (e.g., provider name, token counts).
 */
public record OrasakaChatResponse(
    String content, String conversationId, Map<String, Object> metadata) {}
