/* eslint-disable */
"use client";

import * as React from "react";
import Link from "next/link";
import { useTranslation } from "@/core/context/LocaleContext";
import type { Locale } from "@/core/context/translations.types";

const LOCALES: { code: Locale; label: string }[] = [
  { code: "en", label: "EN" },
  { code: "fr", label: "FR" },
];

const CONTENT = {
  en: {
    title: "Terms of Service",
    subtitle: "Local software license & responsibilities.",
    lastUpdated: "Last updated: June 2026",
    intro:
      "Welcome to Orasaka. By executing this software on your bare-metal hardware, you agree to these Terms of Service. Please read them carefully to understand your rights and licensing terms.",
    sections: [
      {
        title: "1. Software License",
        text: "Orasaka is licensed under the permissive MIT Open Source License. You are free to run, copy, modify, merge, publish, or distribute the software client binaries and source code, subject to compiling terms.",
      },
      {
        title: "2. Local Execution Invariant",
        text: "The software executes natively within your own user context. You assume all operational responsibility, including managing local system resources, database storage, and securing private environment files.",
      },
      {
        title: "3. AI Predictions & Liability",
        text: "Orasaka coordinates predictions generated by local (Ollama/Metal) and cloud models. You acknowledge that AI output is probabilistic, and Orasaka is not liable for incorrect code, hallucinations, or compilation errors.",
      },
      {
        title: "4. Third-Party API Terms",
        text: "Any commercial provider keys (Gemini, Anthropic, OpenAI) entered into the Settings panel connect directly to those third-party services. You are solely responsible for billing and compliance with their API usage rules.",
      },
    ],
    backToLogin: "Back to login",
  },
  fr: {
    title: "Conditions d'Utilisation",
    subtitle: "Licence logicielle locale et responsabilités.",
    lastUpdated: "Dernière mise à jour : Juin 2026",
    intro:
      "Bienvenue sur Orasaka. En exécutant ce logiciel sur votre matériel local, vous acceptez ces Conditions d'Utilisation. Veuillez les lire attentivement pour comprendre vos droits et les termes de licence.",
    sections: [
      {
        title: "1. Licence du Logiciel",
        text: "Orasaka est distribué sous la licence libre MIT. Vous êtes libre d'exécuter, copier, modifier, fusionner, publier ou distribuer les binaires du client et le code source, selon les termes de la licence.",
      },
      {
        title: "2. Invariant d'Exécution Locale",
        text: "Le logiciel s'exécute nativement dans le contexte de votre utilisateur local. Vous assumez toute responsabilité opérationnelle, y compris la gestion des ressources système locales et la sécurisation des secrets.",
      },
      {
        title: "3. Prédictions IA et Responsabilité",
        text: "Orasaka orchestre les prédictions générées par des modèles locaux et cloud. Vous reconnaissez que les résultats de l'IA sont probabilistes et qu'Orasaka n'est pas responsable du code incorrect ou des hallucinations.",
      },
      {
        title: "4. API de Fournisseurs Tiers",
        text: "Toutes les clés d'API (Gemini, Anthropic, OpenAI) saisies dans les Paramètres connectent directement à ces services. Vous êtes seul responsable de la facturation et du respect de leurs règles d'utilisation.",
      },
    ],
    backToLogin: "Retour à la connexion",
  },
};

export default function TermsPage() {
  const { t, locale, setLocale } = useTranslation();
  const c = CONTENT[locale] || CONTENT.en;

  return (
    <main className="min-h-screen flex flex-col items-center p-6 bg-[var(--surface-0)] ambient-grid w-full overflow-y-auto">
      {/* Navbar header */}
      <header className="w-full max-w-4xl flex items-center justify-between py-4 mb-6 border-b border-[var(--border-subtle)]">
        <Link href="/login" className="flex items-center gap-2 hover:opacity-80 transition-opacity">
          <img
            src="/logo.svg"
            alt="Orasaka Logo"
            width={24}
            height={24}
            className="w-6 h-6"
          />
          <span className="text-lg font-bold tracking-tight text-[var(--text-primary)]">
            Orasaka
          </span>
        </Link>

        <Link
          href="/login"
          className="text-xs font-semibold px-3 py-1.5 rounded-lg border border-[var(--border-default)] hover:border-[var(--accent)] transition-colors hover:text-[var(--accent)] text-[var(--text-secondary)]"
        >
          {c.backToLogin}
        </Link>
      </header>

      {/* Main Glass Card container */}
      <article className="w-full max-w-4xl glass-card rounded-2xl p-6 md:p-10 space-y-8 animate-fade-up shadow-2xl">
        <header className="space-y-2 border-b border-[var(--border-subtle)] pb-6">
          <h1 className="text-3xl font-extrabold tracking-tight text-[var(--text-primary)] md:text-4xl">
            {c.title}
          </h1>
          <p className="text-[var(--accent)] font-medium text-sm md:text-base">
            {c.subtitle}
          </p>
          <p className="text-xs text-[var(--text-muted)] pt-1">{c.lastUpdated}</p>
        </header>

        <p className="text-[var(--text-secondary)] text-sm md:text-base leading-relaxed">
          {c.intro}
        </p>

        <div className="grid gap-6 md:grid-cols-2 pt-2">
          {c.sections.map((section, idx) => (
            <section
              key={idx}
              className="p-5 rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-1)] hover:border-[var(--border-strong)] transition-colors duration-200"
            >
              <h2 className="text-base font-bold text-[var(--text-primary)] mb-2">
                {section.title}
              </h2>
              <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
                {section.text}
              </p>
            </section>
          ))}
        </div>
      </article>

      {/* Public Footer */}
      <footer className="w-full max-w-4xl flex items-center justify-between py-6 mt-6 border-t border-[var(--border-subtle)] text-xs text-[var(--text-muted)]">
        <div className="flex gap-4">
          <Link href="/privacy" className="hover:text-[var(--accent)] transition-colors">
            {t.auth.legalPrivacy}
          </Link>
          <Link href="/terms" className="hover:text-[var(--accent)] transition-colors underline">
            {t.auth.legalTerms}
          </Link>
          <Link href="/contact" className="hover:text-[var(--accent)] transition-colors">
            {t.auth.legalContact}
          </Link>
        </div>

        <nav className="auth-lang-switcher-inline" aria-label={t.auth.langSwitchLabel}>
          {LOCALES.map(({ code, label }, i) => (
            <React.Fragment key={code}>
              {i > 0 && <span className="auth-lang-divider">/</span>}
              <button
                type="button"
                className="auth-lang-link"
                data-active={locale === code}
                onClick={() => setLocale(code)}
              >
                {label}
              </button>
            </React.Fragment>
          ))}
        </nav>
      </footer>
    </main>
  );
}
