/**
 * @file init.command.ts
 * @description Interactive workspace initialization command with guided configuration.
 * Sets up directories, generates secure .env, copies docker-compose sheets,
 * and runs an optional configuration wizard for environment tuning.
 */

import { Command } from "commander";
import * as fs from "node:fs";
import * as path from "node:path";
import * as crypto from "node:crypto";
import chalk from "chalk";
import {
  intro,
  outro,
  confirm,
  select,
  text,
  note,
  logSuccess,
  logWarning,
  logStep,
  createSpinner,
  handleCancel,
  isCancel,
} from "../ui/prompts";
import {
  resolveWorkspaceRoot,
  resolveEnvFile,
  resolveComposeFile,
  writeEnvFile,
  hasTool,
  getSystemInfo,
} from "../ui/platform";

/** Generates a cryptographically secure hex string. */
function secureHex(bytes: number): string {
  return crypto.randomBytes(bytes).toString("hex");
}

/** All workspace directories to create. */
function getWorkspaceDirs(root: string): string[] {
  return [
    path.join(root, "var", "orasaka-uploads"),
    path.join(root, "var", "temp"),
    path.join(root, "var", "logs"),
    path.join(root, "infra"),
    path.join(root, "infra", "local-db"),
  ];
}

/** The Docker Compose template for local infrastructure. */
function getDefaultComposeYml(): string {
  return `version: '3.8'
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: orasaka-postgres
    environment:
      POSTGRES_DB: \${POSTGRES_DB:-orasaka_db}
      POSTGRES_USER: \${SPRING_DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: \${SPRING_DATASOURCE_PASSWORD:?SPRING_DATASOURCE_PASSWORD must be set}
    command: postgres -c shared_buffers=256MB -c max_connections=100
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./local-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${SPRING_DATASOURCE_USERNAME:-postgres} -d \${POSTGRES_DB:-orasaka_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mcp-debug-server:
    image: node:20-slim
    container_name: orasaka-mcp-debug
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "npm init -y && 
             npm install @modelcontextprotocol/sdk && 
             node -e '
               const { Server } = require(\\\\"@modelcontextprotocol/sdk/server/index.js\\\\");
               const { StdioServerTransport } = require(\\\\"@modelcontextprotocol/sdk/server/stdio.js\\\\");
               const { ListToolsRequestSchema } = require(\\\\"@modelcontextprotocol/sdk/types.js\\\\");
               const server = new Server({ name: \\\\"debug-server\\\\", version: \\\\"1.0.0\\\\" }, { capabilities: { tools: {} } });
               server.setRequestHandler(ListToolsRequestSchema, () => ({ tools: [{ name: \\\\"echo\\\\", description: \\\\"Echo input\\\\" }] }));
               require(\\\\"http\\\\").createServer((req, res) => res.end(\\\\"ok\\\\")).listen(8080);
               const transport = new StdioServerTransport();
               server.connect(transport).then(() => console.log(\\\\"MCP Debug Server connected via Stdio\\\\"));
             '"
    ports:
      - "8084:8080"

  redis:
    image: redis:7-alpine
    container_name: orasaka-redis
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru --save 900 1 --appendonly no
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    container_name: orasaka-rabbitmq
    hostname: localhost
    environment:
      RABBITMQ_DEFAULT_USER: \${SPRING_RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: \${SPRING_RABBITMQ_PASSWORD:-guest}
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgvector_data:
`;
}

/** Default .env template with secure defaults. */
function getDefaultEnvTemplate(): string {
  return [
    "# ──────────────────────────────────────────────────────",
    "# ORASAKA ENVIRONMENT CONFIGURATION",
    "# Generated by: npx orasaka init",
    `# Timestamp: ${new Date().toISOString()}`,
    "# ──────────────────────────────────────────────────────",
    "",
    "# ─── Server & Network ────────────────────────────────",
    "PORT=8080",
    "GATEWAY_CORS_ALLOWED_ORIGINS=http://localhost:3000",
    "UI_URL=http://localhost:3000",
    "",
    "# ─── PostgreSQL ──────────────────────────────────────",
    "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/orasaka_db",
    "SPRING_DATASOURCE_USERNAME=orasaka_admin",
    `SPRING_DATASOURCE_PASSWORD=${secureHex(16)}`,
    "",
    "# ─── RabbitMQ ─────────────────────────────────────────",
    "SPRING_RABBITMQ_HOST=localhost",
    "SPRING_RABBITMQ_PORT=5672",
    "",
    "# ─── Redis ────────────────────────────────────────────",
    "REDIS_URL=redis://localhost:6379",
    "",
    "# ─── Docker Containers ────────────────────────────────",
    "POSTGRES_CONTAINER=orasaka-postgres",
    "REDIS_CONTAINER=orasaka-redis",
    "RABBITMQ_CONTAINER=orasaka-rabbitmq",
    "",
    "# ─── AI Provider ─────────────────────────────────────",
    "DEFAULT_PROVIDER=ollama",
    "OLLAMA_BASE_URL=http://localhost:11434",
    "OLLAMA_MODEL=phi3:mini",
    "OLLAMA_EMBEDDING_MODEL=nomic-embed-text:latest",
    "ROUTER_PROVIDER=ollama",
    "ROUTER_MODEL=phi3:mini",
    "OLLAMA_NUM_PARALLEL=1",
    "OLLAMA_KEEP_ALIVE=24h",
    "",
    "# ─── Workers ──────────────────────────────────────────",
    "VIDEO_WORKER_PORT=8188",
    "IMAGE_WORKER_PORT=8085",
    "UPLOAD_DIR=var/orasaka-uploads",
    "",
    "# ─── Security ─────────────────────────────────────────",
    `CRYPTO_KEY=${secureHex(16)}`,
    `CRYPTO_SALT=${secureHex(8)}`,
    "",
    "# ─── Logs ─────────────────────────────────────────────",
    "LOG_DIR=var/logs",
    "GATEWAY_LOG=var/logs/gateway.log",
    "AUTOMATION_WORKER_LOG=var/logs/automation-worker.log",
    "IMAGE_WORKER_LOG=var/logs/image-worker.log",
    "VIDEO_WORKER_LOG=var/logs/video-worker.log",
    "IMAGE_GEN_WORKER_LOG=var/logs/image-generation-worker.log",
  ].join("\n");
}

export const initCommand = new Command("init")
  .description("Initialize workspace — directories, secure .env, Docker compose, and guided setup")
  .option("-f, --force", "Force overwrite of existing environment configuration files")
  .option("-y, --yes", "Skip interactive prompts and use all defaults")
  .action(async (options: { force?: boolean; yes?: boolean }) => {
    const workspaceRoot = resolveWorkspaceRoot();
    const isInteractive = !options.yes;

    await intro(chalk.cyan.bold("🥷 Orasaka Workspace Initializer"));

    // ─── System greeting ──────────────────────────────────────
    const sys = getSystemInfo();
    const sysLines = [
      `${chalk.yellow("Platform")}     ${sys.platform} / ${sys.arch}`,
      `${chalk.yellow("CPU")}          ${sys.cpuModel}`,
      `${chalk.yellow("Memory")}       ${String(sys.totalMemoryGb)} GB`,
      `${chalk.yellow("Node")}         ${sys.nodeVersion}`,
      `${chalk.yellow("Workspace")}    ${workspaceRoot}`,
    ];

    if (sys.isAppleSilicon) {
      sysLines.push(`${chalk.yellow("Accelerator")}  ${chalk.green("✔ Apple Silicon Metal MPS")}`);
    }

    await note(sysLines.join("\n"), "System Information");

    // ─── Step 1: Create directories ───────────────────────────
    const spinner = await createSpinner();
    spinner.start("Creating workspace directories...");

    const dirs = getWorkspaceDirs(workspaceRoot);
    let dirsCreated = 0;
    for (const d of dirs) {
      if (!fs.existsSync(d)) {
        fs.mkdirSync(d, { recursive: true });
        dirsCreated++;
      }
    }

    spinner.stop(`Directories ready (${String(dirsCreated)} created, ${String(dirs.length - dirsCreated)} already existed)`);

    // ─── Step 2: Generate .env ────────────────────────────────
    const envPath = resolveEnvFile();
    const envExists = fs.existsSync(envPath);

    if (envExists && !options.force) {
      await logWarning(
        ".env already exists. Use " + chalk.cyan("--force") + " to regenerate.\n" +
        "  To edit individual values, use " + chalk.cyan("npx orasaka config") + "."
      );
    } else {
      let shouldGenerate = true;

      if (envExists && options.force && isInteractive) {
        const overwriteConfirm = await confirm({
          message: "Existing .env will be overwritten with fresh secure secrets. Continue?",
          initialValue: false,
        });
        handleCancel(overwriteConfirm);
        shouldGenerate = overwriteConfirm === true;
      }

      if (shouldGenerate) {
        // Try to read from example template first
        let envContent = "";
        const templatePaths = [
          path.join(workspaceRoot, "exemple.env.txt"),
          path.join(workspaceRoot, ".env.example"),
          path.join(workspaceRoot, ".env.template"),
        ];

        let templateFound = false;
        for (const tp of templatePaths) {
          if (fs.existsSync(tp)) {
            envContent = fs.readFileSync(tp, "utf-8");
            templateFound = true;
            await logStep(`Using template: ${path.basename(tp)}`);
            break;
          }
        }

        if (!templateFound) {
          envContent = getDefaultEnvTemplate();
        } else {
          // Inject secure random values into template
          envContent = envContent
            .replace(/SPRING_DATASOURCE_PASSWORD=.*/g, `SPRING_DATASOURCE_PASSWORD=${secureHex(16)}`)
            .replace(/CRYPTO_KEY=.*/g, `CRYPTO_KEY=${secureHex(16)}`)
            .replace(/CRYPTO_SALT=.*/g, `CRYPTO_SALT=${secureHex(8)}`);
        }

        fs.writeFileSync(envPath, envContent, "utf-8");
        await logSuccess("Secure .env generated with cryptographic secrets.");
      }
    }

    // ─── Step 3: Interactive AI provider configuration ────────
    if (isInteractive) {
      const wantsConfigure = await confirm({
        message: "Would you like to configure your AI provider now?",
        initialValue: true,
        active: "Yes, let's configure",
        inactive: "No, use defaults",
      });

      if (!isCancel(wantsConfigure) && wantsConfigure === true) {
        const provider = await select({
          message: "Which AI provider do you want to use?",
          options: [
            { value: "ollama", label: "🦙 Ollama (Local)", hint: "Free, private, runs on your hardware" },
            { value: "openai", label: "🤖 OpenAI", hint: "Requires API key" },
            { value: "anthropic", label: "🧠 Anthropic", hint: "Requires API key" },
          ],
          initialValue: "ollama",
        });

        if (!isCancel(provider)) {
          const updates: Record<string, string> = { DEFAULT_PROVIDER: provider as string };

          if (provider === "ollama") {
            const model = await select({
              message: "Select your default chat model",
              options: [
                { value: "phi3:mini", label: "Phi-3 Mini", hint: "Fast, lightweight (~2GB)" },
                { value: "llama3.2:latest", label: "Llama 3.2", hint: "Meta's latest (~4GB)" },
                { value: "mistral:latest", label: "Mistral 7B", hint: "Strong all-rounder (~4GB)" },
                { value: "qwen2.5:latest", label: "Qwen 2.5", hint: "Alibaba's multilingual (~4GB)" },
                { value: "deepseek-r1:latest", label: "DeepSeek R1", hint: "Reasoning specialist (~4GB)" },
              ],
              initialValue: "phi3:mini",
            });

            if (!isCancel(model)) {
              updates["OLLAMA_MODEL"] = model as string;
              updates["ROUTER_MODEL"] = model as string;
            }
          } else if (provider === "openai") {
            const apiKey = await text({
              message: "Enter your OpenAI API key",
              placeholder: "sk-...",
              validate: (val: string) =>
                val.startsWith("sk-") ? undefined : "OpenAI key should start with 'sk-'",
            });
            if (!isCancel(apiKey)) {
              updates["OPENAI_API_KEY"] = apiKey as string;
            }
          } else if (provider === "anthropic") {
            const apiKey = await text({
              message: "Enter your Anthropic API key",
              placeholder: "sk-ant-...",
              validate: (val: string) =>
                val.startsWith("sk-ant-") ? undefined : "Anthropic key should start with 'sk-ant-'",
            });
            if (!isCancel(apiKey)) {
              updates["ANTHROPIC_API_KEY"] = apiKey as string;
            }
          }

          writeEnvFile(envPath, updates);
          await logSuccess(`AI provider configured: ${chalk.cyan(provider as string)}`);
        }
      }
    }

    // ─── Step 4: Docker Compose sheets ────────────────────────
    const composeDest = resolveComposeFile();
    if (!fs.existsSync(composeDest) || options.force) {
      // Try to copy from repository location
      const repoComposeSrc = path.join(workspaceRoot, "infra", "docker-compose.yml");
      if (fs.existsSync(repoComposeSrc) && repoComposeSrc !== composeDest) {
        fs.copyFileSync(repoComposeSrc, composeDest);
        await logSuccess("Copied docker-compose sheets from repository.");
      } else if (!fs.existsSync(composeDest)) {
        fs.writeFileSync(composeDest, getDefaultComposeYml(), "utf-8");
        await logSuccess("Generated default docker-compose.yml.");
      }
    } else {
      await logStep("docker-compose.yml already exists.");
    }

    // ─── Step 5: SQL init scripts ─────────────────────────────
    const initSQLDir = path.join(workspaceRoot, "infra", "local-db");
    const schemaSQL = path.join(initSQLDir, "01-schema.sql");
    const dataSQL = path.join(initSQLDir, "02-data.sql");

    // Copy from known repository locations
    const fallbackDirs = [
      path.join(workspaceRoot, "infra", "local-db"),
    ];

    for (const fallbackDir of fallbackDirs) {
      const srcSchema = path.join(fallbackDir, "01-schema.sql");
      const srcData = path.join(fallbackDir, "02-data.sql");
      if (fs.existsSync(srcSchema) && (!fs.existsSync(schemaSQL) || options.force)) {
        if (srcSchema !== schemaSQL) {
          fs.copyFileSync(srcSchema, schemaSQL);
        }
      }
      if (fs.existsSync(srcData) && (!fs.existsSync(dataSQL) || options.force)) {
        if (srcData !== dataSQL) {
          fs.copyFileSync(srcData, dataSQL);
        }
      }
    }

    // ─── Step 6: Quick prerequisite check ─────────────────────
    const tools = ["docker", "node", "git"];
    const missing: string[] = [];
    for (const tool of tools) {
      if (!hasTool(tool)) missing.push(tool);
    }

    if (missing.length > 0) {
      await logWarning(
        `Missing critical tools: ${chalk.red(missing.join(", "))}\n` +
        `  Run ${chalk.cyan("npx orasaka doctor")} for full diagnostics.`
      );
    }

    // ─── Summary ──────────────────────────────────────────────
    const summary = [
      `${chalk.green("✔")} Workspace directories`,
      `${chalk.green("✔")} Environment configuration (.env)`,
      `${chalk.green("✔")} Docker Compose sheets`,
      `${chalk.green("✔")} PostgreSQL init scripts`,
      "",
      `${chalk.cyan("Next steps:")}`,
      `  ${chalk.white("1.")} ${chalk.cyan("npx orasaka doctor")}  — Verify system requirements`,
      `  ${chalk.white("2.")} ${chalk.cyan("npx orasaka config")}  — Edit environment variables`,
      `  ${chalk.white("3.")} ${chalk.cyan("npx orasaka start")}   — Launch the infrastructure`,
    ];

    await note(summary.join("\n"), "✨ Initialization Complete");
    await outro(chalk.green("Workspace ready. Happy building! 🚀"));
  });
