import { Command } from "commander";
import { createSpinner } from "../ui/prompts";
import { requireAuth } from "../threads";
import { ChatApi } from "../services/chat.api";
import { Logger } from "../ui/logger";
import * as fs from "fs";
import * as path from "path";

// Extract content between ```tsx / ``` markers or similar code blocks
function extractCodeBlock(text: string): string {
  const regex = /```(?:tsx|typescript|jsx|javascript|html)?([\s\S]*?)```/i;
  const match = regex.exec(text);
  if (match?.[1]) {
    return match[1].trim();
  }
  return text.trim();
}

export const generateCommand = new Command("generate")
  .description("Generate software feature/component code and scaffold Next.js blueprint workspace")
  .requiredOption("-f, --feature <prompt>", "Description of the software feature/application to generate")
  .requiredOption("-o, --output <dir>", "Directory path to write the generated blueprint workspace")
  .option("-m, --model <model>", "Specify AI model name (defaults to qwen2.5-coder:7b)")
  .action(async (options: { feature: string; output: string; model?: string }) => {
    const config = requireAuth();

    const outputDir = path.resolve(options.output);
    Logger.info(`Starting Feature-to-Code generation...`);
    Logger.hint(`Feature: "${options.feature}"`);
    Logger.hint(`Target Directory: "${outputDir}"`);
    if (options.model) {
      Logger.hint(`Model: "${options.model}"`);
    }

    const s = await createSpinner();
    s.start("Requesting code generation stream from gateway...");

    let accumulatedContent = "";

    try {
      await ChatApi.streamCodeRest(
        options.feature,
        options.model || "qwen2.5-coder:7b",
        config.token,
        (chunk) => {
          accumulatedContent += chunk;
          s.message(`Streaming generated components... (${accumulatedContent.length} chars)`);
        },
        (err) => {
          throw err;
        },
        () => {
          s.message("Generation stream complete.");
        }
      );

      s.message("Scaffolding Next.js blueprint workspace...");

      // Ensure directory structure
      fs.mkdirSync(path.join(outputDir, "src/app"), { recursive: true });

      // 1. package.json
      const packageJson = {
        name: "nextjs-blueprint",
        version: "0.1.0",
        private: true,
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
          lint: "next lint"
        },
        dependencies: {
          "next": "14.2.3",
          "react": "^18",
          "react-dom": "^18"
        },
        devDependencies: {
          "@types/node": "^20",
          "@types/react": "^18",
          "@types/react-dom": "^18",
          "typescript": "^5"
        }
      };
      fs.writeFileSync(
        path.join(outputDir, "package.json"),
        JSON.stringify(packageJson, null, 2),
        "utf-8"
      );

      // 2. tsconfig.json
      const tsConfig = {
        compilerOptions: {
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          plugins: [
            {
              name: "next"
            }
          ],
          paths: {
            "@/*": ["./src/*"]
          }
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        exclude: ["node_modules"]
      };
      fs.writeFileSync(
        path.join(outputDir, "tsconfig.json"),
        JSON.stringify(tsConfig, null, 2),
        "utf-8"
      );

      // 3. src/app/layout.tsx
      const layoutContent = `import React from 'react';

export const metadata = {
  title: 'Next.js Blueprint App',
  description: 'Generated by Orasaka Feature-to-Code Pipeline',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
      fs.writeFileSync(path.join(outputDir, "src/app/layout.tsx"), layoutContent, "utf-8");

      // 4. src/app/page.tsx (using the generated/extracted code)
      const pageCode = extractCodeBlock(accumulatedContent);
      fs.writeFileSync(path.join(outputDir, "src/app/page.tsx"), pageCode, "utf-8");

      s.stop("Blueprint workspace successfully scaffolded!");
      Logger.success(`✓ Code components written to: ${path.join(outputDir, "src/app/page.tsx")}`);
    } catch (err: unknown) {
      s.stop("Generation failed");
      const msg = err instanceof Error ? err.message : "Unknown error";
      Logger.error(`Feature-to-Code Scaffolding Failed: ${msg}`);
      process.exit(1);
    }
  });
